version: "3.9"

services:
  backend:
    build: ./python
    container_name: ocr
    ports:
      - "8000:8000"

  frontend:
    build: ./
    container_name: vite
    ports:
      - "5173:5173"
    depends_on:
      - backend
